/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computing2project;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Mikymus Victorius
 */
public class EmployeeLoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeLoginPage.class.getName());

    /**
     * Creates new form EmployeeLoginPage
     */
    public EmployeeLoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeLoginImage = new javax.swing.JLabel();
        EmployeeIDLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        EmployeeIDField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        ShowPasswordCheckBox = new javax.swing.JCheckBox();
        LogInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmployeeLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/sharpen image.png"))); // NOI18N

        EmployeeIDLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        EmployeeIDLabel.setForeground(new java.awt.Color(204, 0, 0));
        EmployeeIDLabel.setText(" Employee ID:");

        PasswordLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(204, 0, 0));
        PasswordLabel.setText("Password:");

        EmployeeIDField.setBackground(new java.awt.Color(204, 0, 0));
        EmployeeIDField.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        EmployeeIDField.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeIDField.setToolTipText("Employee ID Here");
        EmployeeIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIDFieldActionPerformed(evt);
            }
        });

        PasswordField.setBackground(new java.awt.Color(204, 0, 0));
        PasswordField.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        ShowPasswordCheckBox.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ShowPasswordCheckBox.setForeground(new java.awt.Color(204, 0, 0));
        ShowPasswordCheckBox.setText("Show Password");
        ShowPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordCheckBoxActionPerformed(evt);
            }
        });

        LogInButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(204, 0, 0));
        LogInButton.setText("Log In");
        LogInButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Motor PH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmployeeLoginImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLabel)
                            .addComponent(EmployeeIDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowPasswordCheckBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmployeeIDField)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EmployeeLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeIDLabel)
                    .addComponent(EmployeeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPasswordCheckBox)
                .addGap(18, 18, 18)
                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIDFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EmployeeIDFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
        PasswordField.setEchoChar('•');
        
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ShowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
        if (ShowPasswordCheckBox.isSelected()) {
        PasswordField.setEchoChar((char) 0); // Show password
        } 
        else {
        PasswordField.setEchoChar('•'); // Hide password
        }
    }//GEN-LAST:event_ShowPasswordCheckBoxActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        // TODO add your handling code here:
        String employeeId = EmployeeIDField.getText();
        String portalpassword = new String(PasswordField.getPassword());

        if (employeeId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your employee number");
            return;
        } 
        if (portalpassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your password");
            return;
        }

        if (validateCredentials(employeeId, portalpassword)) {
        JOptionPane.showMessageDialog(this, "Log in successful");

            try {
                // Pass employeeNumber to the dashboard if needed
                EmployeeDetailPage employeeDetail = new EmployeeDetailPage(employeeId);
                employeeDetail.setVisible(true);

                // Close the current login window
                this.dispose();
            } 
            catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to start application: " + e.getMessage(), "Startup Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            }

        } 
        else {
        JOptionPane.showMessageDialog(this, "Incorrect employee number or password!", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LogInButtonActionPerformed
    
    private boolean validateCredentials(String employeeNumber, String portalpassword) {
    try (BufferedReader reader = new BufferedReader(new FileReader("src/DataFiles/employees.csv"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length >= 12 && parts[0].equals(employeeNumber) && parts[1].equals(portalpassword)) {
                // Credentials match
                return true;
            }
        }
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error occurred while logging in. Please try again later.");
        ex.printStackTrace();
    }
    return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeLoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmployeeIDField;
    private javax.swing.JLabel EmployeeIDLabel;
    private javax.swing.JLabel EmployeeLoginImage;
    private javax.swing.JButton LogInButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JCheckBox ShowPasswordCheckBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
