/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computing2project;

/**
 *
 * @author Mikymus Victorius
 */
public class LogInSelectPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogInSelectPage.class.getName());

    /**
     * Creates new form LogInSelectPage
     */
    public LogInSelectPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInSelectImage = new javax.swing.JLabel();
        HeaderMotorPH = new javax.swing.JLabel();
        EmployeeButton = new javax.swing.JButton();
        AdminStaffButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setMinimumSize(new java.awt.Dimension(669, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogInSelectImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/sharpen image.png"))); // NOI18N
        LogInSelectImage.setToolTipText("");
        getContentPane().add(LogInSelectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, -1, -1));

        HeaderMotorPH.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 55)); // NOI18N
        HeaderMotorPH.setForeground(new java.awt.Color(204, 0, 0));
        HeaderMotorPH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderMotorPH.setText("MOTOR PH");
        getContentPane().add(HeaderMotorPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 669, -1));

        EmployeeButton.setBackground(new java.awt.Color(204, 0, 0));
        EmployeeButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        EmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeButton.setText("Employee");
        EmployeeButton.setBorder(null);
        EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 385, 161, 42));

        AdminStaffButton.setBackground(new java.awt.Color(204, 0, 0));
        AdminStaffButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        AdminStaffButton.setForeground(new java.awt.Color(255, 255, 255));
        AdminStaffButton.setText("Admin Staff");
        AdminStaffButton.setBorder(null);
        AdminStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminStaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdminStaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 385, 161, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeLoginPage employeelogin = new EmployeeLoginPage();
        
        employeelogin.setVisible(true);
        
        //close previous window
        this.dispose();
    }//GEN-LAST:event_EmployeeButtonActionPerformed

    private void AdminStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminStaffButtonActionPerformed
        // TODO add your handling code here:
        AdminLoginPage adminLogin = new AdminLoginPage();
        
        adminLogin.setVisible(true);
        
        //close previous window
        this.dispose();
    }//GEN-LAST:event_AdminStaffButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogInSelectPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminStaffButton;
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JLabel HeaderMotorPH;
    private javax.swing.JLabel LogInSelectImage;
    // End of variables declaration//GEN-END:variables
}
